name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            frontend/node_modules
            crowdloan-ui/node_modules
          key: ${{ runner.os }}-lint-${{ hashFiles('frontend/package-lock.json', 'crowdloan-ui/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-lint-
          
      - name: Install dependencies
        run: |
          cd frontend && npm ci --legacy-peer-deps
          cd ../crowdloan-ui && npm ci --legacy-peer-deps
          
      - name: Lint frontend
        run: |
          cd frontend
          npm run lint -- --max-warnings=0
          
      - name: Lint crowdloan
        run: |
          cd crowdloan-ui
          npm run lint -- --max-warnings=0
          
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          cache: true
          
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: chain -> target
          
      - name: Rust format check
        run: |
          cd chain
          cargo fmt --all -- --check
          
      - name: Rust clippy check
        run: |
          cd chain
          cargo clippy -- -D warnings 